version: '3.8'

services:
  sim_engine_api:
    environment:
      - PORT=${PORT}
      - FLASK_ENV=development
    build:
      context: .
      dockerfile: api_Dockerfile
    container_name: sim_engine_api
    ports:
      - "${PORT}:${PORT}"
    restart: always